# Generated by Django 3.0.7 on 2020-09-06 07:57

from django.db import migrations, models
import django.db.models.deletion
import students.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teachers', '0001_initial'),
        ('parents', '0001_initial'),
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(choices=[('1st Term', '1st Term'), ('2nd Term', '2nd Term'), ('3rd Term', '3rd Term')], max_length=20)),
                ('year', models.SmallIntegerField()),
                ('current_session', models.BooleanField(default=False)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admins.School')),
            ],
            options={
                'ordering': ['-year', '-term'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_no', models.CharField(blank=True, max_length=100, null=True)),
                ('photo', models.ImageField(default='default.jpg', upload_to='Student_Pictures')),
                ('address', models.CharField(max_length=100, null=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('sex', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=10, null=True)),
                ('state_of_origin', models.CharField(max_length=30, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(auto_now=True)),
                ('Class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teachers.Class')),
                ('parents', models.ManyToManyField(to='parents.Parent')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='School_activity_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Activity_type', models.CharField(max_length=250)),
                ('Activity_date_and_time', models.DateTimeField(auto_now=True)),
                ('Activity_info', models.CharField(max_length=500)),
                ('viewed', models.BooleanField(default=False)),
                ('Class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.Class')),
            ],
            options={
                'ordering': ['-Activity_date_and_time'],
            },
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=40)),
                ('test', models.FloatField()),
                ('exam', models.FloatField()),
                ('comment', models.CharField(choices=[('excellent', 'excellent'), ('good', 'good'), ('average', 'average'), ('fair', 'fair'), ('poor', 'poor')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('Class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.Class')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Student')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Term')),
            ],
            options={
                'ordering': ['student'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(validators=[students.models.prevent_future_dates])),
                ('Class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.Class', unique_for_date='date')),
                ('present_students', models.ManyToManyField(related_name='attendance', to='students.Student')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AddConstraint(
            model_name='term',
            constraint=models.UniqueConstraint(fields=('term', 'year', 'school'), name='unique_term'),
        ),
        migrations.AddConstraint(
            model_name='performance',
            constraint=models.UniqueConstraint(fields=('term', 'subject', 'student'), name='unique_performance'),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('Class', 'date'), name='unique_attendance'),
        ),
    ]
