# Generated by Django 3.0.7 on 2020-09-29 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='email',
            new_name='student_email',
        ),
    ]
