# Generated by Django 3.0.3 on 2020-03-16 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='term',
            options={'ordering': ['-year', '-term']},
        ),
        migrations.AlterField(
            model_name='term',
            name='term',
            field=models.CharField(choices=[('1st Term', '1st Term'), ('2nd Term', '2nd Term'), ('3rd Term', '3rd Term')], max_length=20),
        ),
    ]
