# Generated by Django 3.0.3 on 2020-06-18 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0002_remove_parent_school'),
        ('students', '0003_remove_student_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='parent',
        ),
        migrations.AddField(
            model_name='student',
            name='parents',
            field=models.ManyToManyField(to='parents.Parent'),
        ),
    ]
