# Generated by Django 3.0.3 on 2020-06-24 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0013_auto_20200618_1640'),
        ('students', '0004_auto_20200618_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='school',
            field=models.ForeignKey(default=17, on_delete=django.db.models.deletion.CASCADE, to='admins.School'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='term',
            constraint=models.UniqueConstraint(fields=('term', 'year'), name='unique_term'),
        ),
    ]
