# Generated by Django 3.0.3 on 2020-06-24 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_auto_20200624_1434'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='term',
            constraint=models.CheckConstraint(check=models.Q(year__lt=2020), name='previous_year'),
        ),
    ]
