# Generated by Django 3.0.3 on 2020-06-24 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_auto_20200624_1715'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='term',
            name='previous_year',
        ),
        migrations.AddConstraint(
            model_name='term',
            constraint=models.CheckConstraint(check=models.Q(year__gte=2020), name='previous_year'),
        ),
    ]
