# Generated by Django 3.0.3 on 2020-06-25 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_auto_20200624_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='religion',
        ),
        migrations.RemoveField(
            model_name='student',
            name='state_of_residence',
        ),
    ]
