# Generated by Django 3.0.7 on 2020-07-14 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_auto_20200625_0950'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='performance',
            options={'ordering': ['student']},
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='term',
        ),
        migrations.RemoveField(
            model_name='performance',
            name='total',
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('Class', 'date'), name='unique_attendance'),
        ),
        migrations.AddConstraint(
            model_name='performance',
            constraint=models.UniqueConstraint(fields=('term', 'subject', 'student'), name='unique_performance'),
        ),
    ]
