# Generated by Django 3.0.7 on 2020-07-14 14:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_auto_20200714_1523'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.CheckConstraint(check=models.Q(date__lte=datetime.date(2020, 7, 14)), name='prevent_future_dates'),
        ),
    ]
