# Generated by Django 3.0.7 on 2020-07-15 14:36

from django.db import migrations, models
import students.models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_auto_20200714_1531'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='attendance',
            name='prevent_future_dates',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(validators=[students.models.prevent_future_dates]),
        ),
    ]
