# Generated by Django 3.0.7 on 2020-07-22 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0017_delete_school_activity_log'),
        ('teachers', '0006_auto_20200715_2209'),
        ('students', '0012_auto_20200715_2209'),
    ]

    operations = [
        migrations.CreateModel(
            name='School_activity_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Activity_type', models.CharField(max_length=250)),
                ('Activity_date_and_time', models.DateTimeField(auto_now=True)),
                ('Activity_info', models.CharField(max_length=500)),
                ('viewed', models.BooleanField(default=False)),
                ('Class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.Class')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admins.School')),
            ],
            options={
                'ordering': ['-Activity_date_and_time'],
            },
        ),
    ]
