# Generated by Django 3.0.7 on 2020-07-29 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_school_activity_log'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['name']},
        ),
    ]
