# Generated by Django 3.0.7 on 2020-07-30 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_auto_20200729_2224'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='term',
            name='unique_term',
        ),
        migrations.AddConstraint(
            model_name='term',
            constraint=models.UniqueConstraint(fields=('term', 'year', 'school'), name='unique_term'),
        ),
    ]
