# Generated by Django 3.0.7 on 2020-07-30 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0015_auto_20200730_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='term',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='students.Term'),
            preserve_default=False,
        ),
    ]
