# Generated by Django 3.0.7 on 2020-08-03 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0016_auto_20200730_1353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school_activity_log',
            name='school',
        ),
    ]
