# Generated by Django 3.0.7 on 2020-08-03 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0003_auto_20200625_0950'),
        ('students', '0017_remove_school_activity_log_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='parents',
            field=models.ManyToManyField(null=True, to='parents.Parent'),
        ),
    ]
