# Generated by Django 3.0.7 on 2020-08-03 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0003_auto_20200625_0950'),
        ('students', '0018_auto_20200803_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='parents',
            field=models.ManyToManyField(to='parents.Parent'),
        ),
    ]
