# Generated by Django 3.0.7 on 2020-08-04 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0010_auto_20200803_1619'),
        ('students', '0019_auto_20200803_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teachers.Class'),
        ),
    ]
