# Generated by Django 3.0.7 on 2020-08-04 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0010_auto_20200803_1619'),
        ('students', '0020_auto_20200804_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Class',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, to='teachers.Class'),
            preserve_default=False,
        ),
    ]
