# Generated by Django 3.0.7 on 2020-08-25 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0023_auto_20200825_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='subject',
            field=models.CharField(max_length=40),
        ),
    ]
