# Generated by Django 3.0.7 on 2020-08-26 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0024_auto_20200825_2135'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='term',
            name='previous_year',
        ),
        migrations.AddField(
            model_name='term',
            name='current_session',
            field=models.BooleanField(default=False),
        ),
    ]
