# Generated by Django 3.0.7 on 2020-08-29 16:42

import admins.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100, null=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('sex', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=10, null=True)),
                ('state_of_origin', models.CharField(max_length=30, null=True)),
                ('phone_no', models.CharField(max_length=100, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=30, validators=[admins.models.username_exists])),
                ('subject', models.CharField(max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reciever', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=100, unique=True)),
                ('school_address', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('Secondary_School', 'Secondary_School'), ('Primary_School', 'Primary_School')], max_length=30)),
                ('approved', models.BooleanField()),
                ('motto', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(default='default.jpg', upload_to='School_Pictures')),
                ('school_email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schools', to='admins.Admin')),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('message_datetime', models.DateTimeField(auto_now_add=True)),
                ('message_read', models.BooleanField(default=False)),
                ('sent_by', models.CharField(max_length=30, validators=[admins.models.username_exists])),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admins.Conversation')),
            ],
            options={
                'ordering': ['-message_datetime'],
            },
        ),
    ]
