# Generated by Django 3.0.7 on 2020-08-31 19:59

import admins.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='sender',
            field=models.CharField(max_length=30, null=True, validators=[admins.models.username_exists]),
        ),
        migrations.AlterField(
            model_name='messages',
            name='sent_by',
            field=models.CharField(max_length=30, null=True, validators=[admins.models.username_exists]),
        ),
    ]
