# Generated by Django 3.0.7 on 2020-09-02 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0002_auto_20200831_2059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='address',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='sex',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='state_of_origin',
        ),
    ]
