# Generated by Django 3.0.7 on 2020-09-29 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0002_auto_20200911_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='type',
            field=models.CharField(choices=[('Secondary School', 'Secondary School'), ('Primary School', 'Primary School'), ('Others', 'Others')], max_length=30),
        ),
    ]
