# Generated by Django 3.0.3 on 2020-03-16 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0002_auto_20200316_1748'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messages',
            options={'ordering': ['-message_datetime']},
        ),
        migrations.AddField(
            model_name='messages',
            name='message_read',
            field=models.BooleanField(default=False),
        ),
    ]
