# Generated by Django 3.0.3 on 2020-03-17 08:58

import admins.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0005_auto_20200316_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='sent_by',
            field=models.CharField(default='DavoBoss1', max_length=30, validators=[admins.models.username_exists]),
            preserve_default=False,
        ),
    ]
