# Generated by Django 3.0.3 on 2020-03-29 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0006_messages_sent_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Activity_type', models.CharField(max_length=250)),
                ('Activity_date_and_time', models.DateTimeField(auto_now=True)),
                ('Activity_info', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterModelOptions(
            name='messages',
            options={'ordering': ['message_datetime']},
        ),
    ]
