# Generated by Django 3.0.3 on 2020-03-30 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0008_auto_20200330_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='school_activity_log',
            name='viewed',
            field=models.BooleanField(default=False),
        ),
    ]
