# Generated by Django 3.0.3 on 2020-04-17 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0009_school_activity_log_viewed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='school',
        ),
        migrations.AddField(
            model_name='admin',
            name='school',
            field=models.ManyToManyField(to='admins.School'),
        ),
    ]
