# Generated by Django 3.0.3 on 2020-04-18 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0010_auto_20200417_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='school',
            field=models.ManyToManyField(related_name='school', to='admins.School'),
        ),
    ]
