# Generated by Django 3.0.3 on 2020-06-18 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0011_auto_20200418_1307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='school',
        ),
        migrations.AddField(
            model_name='school',
            name='admin',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to='admins.Admin'),
            preserve_default=False,
        ),
    ]
