# Generated by Django 3.0.3 on 2020-06-18 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0012_auto_20200618_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schools', to='admins.Admin'),
        ),
    ]
