# Generated by Django 3.0.3 on 2020-06-25 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0013_auto_20200618_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='marital_status',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='religion',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='state_of_residence',
        ),
        migrations.RemoveField(
            model_name='school',
            name='mission',
        ),
        migrations.RemoveField(
            model_name='school',
            name='school_Anthem',
        ),
        migrations.RemoveField(
            model_name='school',
            name='vision',
        ),
    ]
