# Generated by Django 3.0.7 on 2020-07-22 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0016_auto_20200715_2209'),
    ]

    operations = [
        migrations.DeleteModel(
            name='School_activity_log',
        ),
    ]
