# Generated by Django 3.0.7 on 2020-07-23 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0017_delete_school_activity_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='school',
            field=models.ForeignKey(default=17, on_delete=django.db.models.deletion.CASCADE, to='admins.School'),
            preserve_default=False,
        ),
    ]
