# Generated by Django 3.0.7 on 2020-07-23 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0018_conversation_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='school',
        ),
    ]
