# Generated by Django 3.0.7 on 2020-07-29 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0019_remove_conversation_school'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messages',
            options={'ordering': ['-message_datetime']},
        ),
    ]
