# Generated by Django 3.0.3 on 2020-06-25 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_teacher_activity_log'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='employed_on',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='former_employer',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='marital_status',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='religion',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='state_of_residence',
        ),
    ]
