# Generated by Django 3.0.7 on 2020-07-22 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0006_auto_20200715_2209'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teacher_activity_log',
        ),
    ]
