# Generated by Django 3.0.7 on 2020-07-29 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0007_delete_teacher_activity_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='class_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AddConstraint(
            model_name='class',
            constraint=models.UniqueConstraint(fields=('class_name', 'school'), name='unique_class'),
        ),
    ]
