# Generated by Django 3.0.7 on 2020-08-03 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0008_auto_20200729_2224'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'ordering': ['class_name']},
        ),
    ]
