# Generated by Django 3.0.7 on 2020-08-03 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0009_auto_20200803_1229'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={},
        ),
    ]
