# Generated by Django 3.0.7 on 2020-09-02 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='sex',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='state_of_origin',
        ),
    ]
