# Generated by Django 3.0.3 on 2020-06-18 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='school',
        ),
    ]
