# Generated by Django 3.0.3 on 2020-06-25 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0002_remove_parent_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='marital_status',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='religion',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='state_of_residence',
        ),
    ]
